[build]
  #name = "Hello World"
  type = "executable" #static, shared
  target = "x86_64-linux"
  output-dir = "out/"
  libs = ["math", "io"]
  searchpaths = ["/usr/lib", "/usr/local/lib"]
  sources = ["src/main.rf", "src/player.rf", "src/map.rf"]

[build.features]
  show_parse_tree = false
  generate_asm = true
